# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 17:39
from __future__ import unicode_literals

import dafousers.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Aktiv'), (2, 'Blokeret'), (3, 'Deaktiveret')], default=1, verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordUserHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.CharField(max_length=2048, verbose_name='\xc6ndret af')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Seneste opdatering')),
                ('status', models.IntegerField(choices=[(1, 'Aktiv'), (2, 'Blokeret'), (3, 'Deaktiveret')], default=1, verbose_name='Status')),
                ('fullname', models.CharField(blank=True, default='', max_length=2048, verbose_name='Fulde navn')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('organisation', models.TextField(blank=True, default='', verbose_name='Information om brugerens organisation')),
                ('encrypted_password', models.CharField(blank=True, default='', max_length=4096, verbose_name='Krypteret password')),
                ('person_identification', models.UUIDField(blank=True, default='', null=True, verbose_name='Grunddata personidentifikation UUID')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, dafousers.models.HistoryForEntity),
        ),
        migrations.CreateModel(
            name='SystemRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=2048, verbose_name='Navn')),
                ('role_type', models.IntegerField(choices=[(1, 'Servicerolle'), (2, 'Entitetsrolle'), (3, 'Attributrolle'), (4, 'Tilpasset rolletype')], default=4, verbose_name='Type')),
                ('target_name', models.CharField(blank=True, max_length=2048, verbose_name='Objekt rollen giver adgang til')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dafousers.SystemRole', verbose_name='For\xe6ldre-rolle')),
            ],
        ),
        migrations.CreateModel(
            name='UserIdentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=2048, verbose_name='Bruger identifikation (e-mail adresse)')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, verbose_name='Navn')),
                ('created_by', models.CharField(max_length=2048, verbose_name='Oprettet af')),
                ('system_roles', models.ManyToManyField(blank=True, to='dafousers.SystemRole', verbose_name='Tilknyttede systemroller')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordUser',
            fields=[
                ('accessaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dafousers.AccessAccount')),
                ('changed_by', models.CharField(max_length=2048, verbose_name='\xc6ndret af')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Seneste opdatering')),
                ('fullname', models.CharField(blank=True, default='', max_length=2048, verbose_name='Fulde navn')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('organisation', models.TextField(blank=True, default='', verbose_name='Information om brugerens organisation')),
                ('encrypted_password', models.CharField(blank=True, default='', max_length=4096, verbose_name='Krypteret password')),
                ('person_identification', models.UUIDField(blank=True, default='', null=True, verbose_name='Grunddata personidentifikation UUID')),
            ],
            options={
                'abstract': False,
            },
            bases=('dafousers.accessaccount', models.Model),
        ),
        migrations.AddField(
            model_name='passworduserhistory',
            name='identified_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dafousers.UserIdentification', verbose_name='Identificerer bruger'),
        ),
        migrations.AddField(
            model_name='passworduserhistory',
            name='user_profiles',
            field=models.ManyToManyField(blank=True, to='dafousers.UserProfile', verbose_name='Tilknyttede brugerprofiler'),
        ),
        migrations.AddField(
            model_name='accessaccount',
            name='identified_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dafousers.UserIdentification', verbose_name='Identificerer bruger'),
        ),
        migrations.AddField(
            model_name='accessaccount',
            name='user_profiles',
            field=models.ManyToManyField(blank=True, to='dafousers.UserProfile', verbose_name='Tilknyttede brugerprofiler'),
        ),
        migrations.AddField(
            model_name='passworduserhistory',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dafousers.PasswordUser'),
        ),
    ]
