# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import codecs
import re


def get_sql():
    # Filname is same as this script with extension replaced with .sql
    filename = __file__[:__file__.index(".")] + ".sql"
    f = codecs.open(filename, 'r', encoding="utf8")
    contents = "".join(f.readlines())
    f.close()

    contents = [
        x for x in
        re.split(';\s+GO\s+', contents, flags=re.MULTILINE)
        if x.strip()
    ]

    return contents


class Migration(migrations.Migration):

    dependencies = [(b'dafousers', '0002_initial_data')]

    operations = [migrations.RunSQL(x) for x in get_sql()]
