# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 08:00
from __future__ import unicode_literals

import codecs
import re

from django.conf import settings
from django.db import migrations


def get_sql():
    # If not running an SQL server backend, do not try to import SQL server
    # views.
    if not settings.DATABASES['default']['ENGINE'] == "sqlserver_ado":
        return ["SELECT (1)"]

    # Filname is same as this script with extension replaced with .sql
    filename = __file__[:__file__.rfind(".")] + ".sql"
    f = codecs.open(filename, 'r', encoding="utf8")
    contents = "".join(f.readlines())
    f.close()

    contents = [
        x for x in
        re.split(';\s+GO\s+', contents, flags=re.MULTILINE)
        if x.strip()
    ]

    return contents


class Migration(migrations.Migration):

    dependencies = [(b'dafousers', '0002_initial_data')]

    operations = [migrations.RunSQL(x) for x in get_sql()]
