# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dafousers', '0003_initial_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passworduserhistory',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
    ]
