# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-15 11:24
from __future__ import unicode_literals

import uuid

import dafousers.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'dafousers', '0008_auto_20170814_1247'), (b'dafousers', '0009_auto_20170814_1302'), (b'dafousers', '0010_auto_20170821_1631'), (b'dafousers', '0011_auto_20170821_1648'), (b'dafousers', '0012_auto_20170824_1150'), (b'dafousers', '0013_auto_20170908_1423'), (b'dafousers', '0014_auto_20170908_1423'), (b'dafousers', '0015_auto_20170915_1313')]

    dependencies = [
        ('dafousers', '0007_on-behalf-of_mode_on_certificate_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identityprovideraccount',
            name='NameID format',
        ),
        migrations.RemoveField(
            model_name='identityprovideraccount',
            name='Single-Log-Out Endpoint',
        ),
        migrations.RemoveField(
            model_name='identityprovideraccount',
            name='Single-Sign-On Endpoint',
        ),
        migrations.RemoveField(
            model_name='identityprovideraccount',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='identityprovideraccounthistory',
            name='NameID format',
        ),
        migrations.RemoveField(
            model_name='identityprovideraccounthistory',
            name='Single-Log-Out Endpoint',
        ),
        migrations.RemoveField(
            model_name='identityprovideraccounthistory',
            name='Single-Sign-On Endpoint',
        ),
        migrations.RemoveField(
            model_name='identityprovideraccounthistory',
            name='certificates',
        ),
        migrations.AddField(
            model_name='identityprovideraccount',
            name='idp_type',
            field=models.IntegerField(choices=[(1, 'Prim\xe6r IdP (ingen validering af brugerprofiler)'), (2, 'Sekund\xe6r IdP (kan kun udstede angivne brugerprofiler)')], default=2, verbose_name='IdP type'),
        ),
        migrations.AddField(
            model_name='identityprovideraccount',
            name='userprofile_adjustment_filter_type',
            field=models.IntegerField(choices=[(1, 'Ingen tilpasninger'), (2, 'Fjern angivet prefix'), (2, 'Fjern angivet postfix')], default=1, verbose_name='Tilpasninger til brugerprofil v\xe6rdier'),
        ),
        migrations.AddField(
            model_name='identityprovideraccount',
            name='userprofile_adjustment_filter_value',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='V\xe6rdi brugt ved tilpasning af brugerprofiler'),
        ),
        migrations.AddField(
            model_name='identityprovideraccount',
            name='userprofile_attribute',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='SAML-attribut der indeholder brugerprofiler'),
        ),
        migrations.AddField(
            model_name='identityprovideraccount',
            name='userprofile_attribute_format',
            field=models.IntegerField(choices=[(1, 'Multiv\xe6rdi attribut'), (1, 'Kommasepareret liste')], default=1, verbose_name='Format for brugerprofil attribut'),
        ),
        migrations.AddField(
            model_name='identityprovideraccounthistory',
            name='idp_type',
            field=models.IntegerField(choices=[(1, 'Prim\xe6r IdP (ingen validering af brugerprofiler)'), (2, 'Sekund\xe6r IdP (kan kun udstede angivne brugerprofiler)')], default=2, verbose_name='IdP type'),
        ),
        migrations.AddField(
            model_name='identityprovideraccounthistory',
            name='userprofile_adjustment_filter_type',
            field=models.IntegerField(choices=[(1, 'Ingen tilpasninger'), (2, 'Fjern angivet prefix'), (2, 'Fjern angivet postfix')], default=1, verbose_name='Tilpasninger til brugerprofil v\xe6rdier'),
        ),
        migrations.AddField(
            model_name='identityprovideraccounthistory',
            name='userprofile_adjustment_filter_value',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='V\xe6rdi brugt ved tilpasning af brugerprofiler'),
        ),
        migrations.AddField(
            model_name='identityprovideraccounthistory',
            name='userprofile_attribute',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='SAML-attribut der indeholder brugerprofiler'),
        ),
        migrations.AddField(
            model_name='identityprovideraccounthistory',
            name='userprofile_attribute_format',
            field=models.IntegerField(choices=[(1, 'Multiv\xe6rdi attribut'), (1, 'Kommasepareret liste')], default=1, verbose_name='Format for brugerprofil attribut'),
        ),
        migrations.AlterField(
            model_name='identityprovideraccount',
            name='next_expiration',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='N\xe6ste udl\xf8bsdato for metadata og/eller certifikat'),
        ),
        migrations.AlterField(
            model_name='identityprovideraccount',
            name='organisation',
            field=models.TextField(blank=True, default='', verbose_name='Yderligere information om organisationen'),
        ),
        migrations.AlterField(
            model_name='identityprovideraccounthistory',
            name='next_expiration',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='N\xe6ste udl\xf8bsdato for metadata og/eller certifikat'),
        ),
        migrations.AlterField(
            model_name='identityprovideraccounthistory',
            name='organisation',
            field=models.TextField(blank=True, default='', verbose_name='Yderligere information om organisationen'),
        ),
        migrations.RemoveField(
            model_name='identityprovideraccount',
            name='Navn',
        ),
        migrations.RemoveField(
            model_name='identityprovideraccounthistory',
            name='Navn',
        ),
        migrations.AddField(
            model_name='identityprovideraccount',
            name='name',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='Navn'),
        ),
        migrations.AddField(
            model_name='identityprovideraccounthistory',
            name='name',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='Navn'),
        ),
        migrations.CreateModel(
            name='UpdateTimestamps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, verbose_name='Navn')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beskrivelse')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Opdateret')),
            ],
            options={
                'verbose_name': 'Tidsstempel for opdatering',
                'verbose_name_plural': 'Tidsstempler for opdatering',
            },
        ),
        migrations.AddField(
            model_name='identityprovideraccount',
            name='idp_entity_id',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='EntityID'),
        ),
        migrations.AddField(
            model_name='identityprovideraccounthistory',
            name='idp_entity_id',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='EntityID'),
        ),
        migrations.AddField(
            model_name='identityprovideraccount',
            name='metadata_xml_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads', verbose_name='Metadata-xml-fil'),
        ),
        migrations.AddField(
            model_name='identityprovideraccounthistory',
            name='metadata_xml_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads', verbose_name='Metadata-xml-fil'),
        ),
        migrations.RemoveField(
            model_name='passworduser',
            name='person_identification',
        ),
        migrations.RemoveField(
            model_name='passworduserhistory',
            name='person_identification',
        ),
        migrations.AddField(
            model_name='passworduser',
            name='person_identification',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=40, null=True, verbose_name='Grunddata personidentifikation UUID'),
        ),
        migrations.AddField(
            model_name='passworduserhistory',
            name='person_identification',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=40, null=True, verbose_name='Grunddata personidentifikation UUID'),
        ),
        migrations.CreateModel(
            name='UserProfileHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.CharField(max_length=2048, verbose_name='\xc6ndret af')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Opdateret')),
                ('name', models.CharField(max_length=2048, verbose_name='Navn')),
                ('created_by', models.CharField(max_length=2048, verbose_name='Oprettet af')),
                ('area_restrictions', models.ManyToManyField(blank=True, to=b'dafousers.AreaRestriction', verbose_name='Tilknyttede omr\xe5debegr\xe6nsninger')),
            ],
            bases=(models.Model, dafousers.models.HistoryForEntity),
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['valid_to']},
        ),
        migrations.RemoveField(
            model_name='certificateuser',
            name='next_expiration',
        ),
        migrations.RemoveField(
            model_name='certificateuserhistory',
            name='next_expiration',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='changed_by',
            field=models.CharField(default='admin', max_length=2048, verbose_name='\xc6ndret af'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Opdateret'),
        ),
        migrations.AddField(
            model_name='userprofilehistory',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dafousers.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofilehistory',
            name='system_roles',
            field=models.ManyToManyField(blank=True, to=b'dafousers.SystemRole', verbose_name='Tilknyttede systemroller'),
        ),
    ]
