# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-06 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dafousers', '0009_remove_some_unused_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessaccount',
            name='user_profiles',
            field=models.ManyToManyField(blank=True, to='dafousers.UserProfile', verbose_name='Tildelte brugerprofiler'),
        ),
        migrations.AlterField(
            model_name='certificateuserhistory',
            name='user_profiles',
            field=models.ManyToManyField(blank=True, to='dafousers.UserProfile', verbose_name='Tildelte brugerprofiler'),
        ),
        migrations.AlterField(
            model_name='identityprovideraccount',
            name='idp_entity_id',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='IdP-id'),
        ),
        migrations.AlterField(
            model_name='identityprovideraccount',
            name='idp_type',
            field=models.IntegerField(choices=[(1, 'Prim\xe6r IdP (ingen validering af brugerprofiler)'), (2, 'Sekund\xe6r IdP (kan kun udstede angivne brugerprofiler)')], default=2, verbose_name='IdP-type'),
        ),
        migrations.AlterField(
            model_name='identityprovideraccount',
            name='userprofile_adjustment_filter_type',
            field=models.IntegerField(choices=[(1, 'Ingen tilpasninger'), (2, 'Fjern angivet prefix'), (3, 'Fjern angivet postfix')], default=1, verbose_name='Tilpasninger til brugerprofil v\xe6rdier'),
        ),
        migrations.AlterField(
            model_name='identityprovideraccount',
            name='userprofile_attribute_format',
            field=models.IntegerField(choices=[(1, 'Multiv\xe6rdi attribut'), (2, 'Kommasepareret liste')], default=1, verbose_name='Format for brugerprofil attribut'),
        ),
        migrations.AlterField(
            model_name='identityprovideraccounthistory',
            name='idp_entity_id',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='IdP-id'),
        ),
        migrations.AlterField(
            model_name='identityprovideraccounthistory',
            name='idp_type',
            field=models.IntegerField(choices=[(1, 'Prim\xe6r IdP (ingen validering af brugerprofiler)'), (2, 'Sekund\xe6r IdP (kan kun udstede angivne brugerprofiler)')], default=2, verbose_name='IdP-type'),
        ),
        migrations.AlterField(
            model_name='identityprovideraccounthistory',
            name='user_profiles',
            field=models.ManyToManyField(blank=True, to='dafousers.UserProfile', verbose_name='Tildelte brugerprofiler'),
        ),
        migrations.AlterField(
            model_name='identityprovideraccounthistory',
            name='userprofile_adjustment_filter_type',
            field=models.IntegerField(choices=[(1, 'Ingen tilpasninger'), (2, 'Fjern angivet prefix'), (3, 'Fjern angivet postfix')], default=1, verbose_name='Tilpasninger til brugerprofil v\xe6rdier'),
        ),
        migrations.AlterField(
            model_name='identityprovideraccounthistory',
            name='userprofile_attribute_format',
            field=models.IntegerField(choices=[(1, 'Multiv\xe6rdi attribut'), (2, 'Kommasepareret liste')], default=1, verbose_name='Format for brugerprofil attribut'),
        ),
        migrations.AlterField(
            model_name='passworduser',
            name='organisation',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='Arbejdssted'),
        ),
        migrations.AlterField(
            model_name='passworduserhistory',
            name='organisation',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='Arbejdssted'),
        ),
        migrations.AlterField(
            model_name='passworduserhistory',
            name='user_profiles',
            field=models.ManyToManyField(blank=True, to='dafousers.UserProfile', verbose_name='Tildelte brugerprofiler'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='area_restrictions',
            field=models.ManyToManyField(blank=True, to='dafousers.AreaRestriction', verbose_name='Tildelte omr\xe5deafgr\xe6nsninger'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='system_roles',
            field=models.ManyToManyField(blank=True, to='dafousers.SystemRole', verbose_name='Tildelte systemroller'),
        ),
        migrations.AlterField(
            model_name='userprofilehistory',
            name='area_restrictions',
            field=models.ManyToManyField(blank=True, to='dafousers.AreaRestriction', verbose_name='Tildelte omr\xe5deafgr\xe6nsninger'),
        ),
        migrations.AlterField(
            model_name='userprofilehistory',
            name='system_roles',
            field=models.ManyToManyField(blank=True, to='dafousers.SystemRole', verbose_name='Tildelte systemroller'),
        ),
    ]
