# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-26 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dafousers', '0010_rename_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_time', models.DateTimeField(default=None, null=True, verbose_name='Udstedelsestidspunkt')),
                ('token_data', models.TextField(blank=True, null=True, verbose_name='Token data')),
                ('token_nameid', models.CharField(blank=True, max_length=256, null=True, verbose_name='Token NameID')),
                ('token_on_behalf_of', models.CharField(blank=True, max_length=256, null=True, verbose_name='Token OnBehalfOf')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Eventuel fejlbesked')),
                ('request_service_url', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Udstedt via URL')),
                ('client_ip', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ip p\xe5 klient')),
                ('client_user_agent', models.CharField(blank=True, max_length=1024, null=True, verbose_name='User-Agent p\xe5 klient')),
                ('access_account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dafousers.AccessAccount', verbose_name='Udstedt til konto')),
            ],
            options={
                'verbose_name': 'Udstedt token',
                'verbose_name_plural': 'Udstedte tokens',
            },
        ),
    ]
